wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689269096.566535
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
Episodes:
  desc: null
  value: 10
Learning_rate:
  desc: null
  value: 0.1
Discount_factor:
  desc: null
  value: 0.9
Exploration_rate:
  desc: null
  value: 0.2
