wandb:
  project: "graphql"
#  project: "campus-indoor-model"
  entity: "safecampusrl"

directories:
  results_directory: "results"
  config_directory: "config"
  policy_directory: "policy"

environment:
  environment_id: 'CampusGymEnv-v0'
  seed: 100

alpha: 0.9  # Example alpha value, change as needed
