agent:
  hidden_units: 88
  learning_rate: 0.01
  discount_factor: 0.9
  max_episodes: 8000
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.00001
  batch_size: 64
  learning_rate_decay: 0.999
  min_learning_rate: 0.00001
  replay_memory_capacity: 10000
  target_network_frequency: 50
  softmax_temperature: 0.1
  e_decay_function: 5

