agent:
  hidden_units: 128
  learning_rate: 0.1
  discount_factor: 0.1
  max_episodes: 1000
  batch_size: 64
  e_decay_function: 1
  softmax_temperature: 1.0
  gae_lambda: 0.95
  clip_parameter: 0.2
  n_epochs: 4
  value_loss_coef: 0.5
  entropy_coef: 0.01
  clip_param: 0.2


