agent:
  learning_rate: 0.5
  discount_factor: 0.9
  max_episodes: 5000
  exploration_rate: 1.0
  min_exploration_rate: 0.000001
  exploration_decay_rate: 0.001 # for exponential decay linear is 0.9999
  checkpoint_interval: 100 # Save model checkpoint after every 100 episodes
  logging_file: "agent_log.txt" # Specify the name of the logging file

#checkpoint_interval
#100
#discount_factor
#0.8
#exploration_decay_rate
#0.001
#exploration_rate
#1
#learning_rate
#0.0001
#logging_file
#"agent_log.txt"
#max_episodes
#10,000
#min_exploration_rate
#0.000001
#alpha
#0.9