agent:
  learning_rate: 0.1
  discount_factor: 0.99
  max_episodes: 10
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.995
  checkpoint_interval: 2 # Save model checkpoint after every 100 episodes
  logging_file: "agent_log.txt" # Specify the name of the logging file

