wandb:
  project: "indoor-model"
  entity: "leezo"

directories:
  results_directory: "results"
  config_directory: "config"

environment:
  environment_id: 'CampusGymEnv-v0'

alpha: 0.5  # Example alpha value, change as needed
