# sweep.yaml
method: grid
metric:
  name: average_return
  goal: maximize
parameters:
  alpha:
    values: [0.1, 0.3, 0.5, 0.7, 0.9] # example alpha values
  learning_rate:
    values: [0.01, 0.03, 0.05, 0.07, 0.1]
  discount_factor:
    values: [0.8, 0.85, 0.9, 0.95, 0.99]
  exploration_rate:
    values: [0.01, 0.03, 0.05, 0.07, 0.1]
