# sweep.yaml
method: grid
metric:
  name: average_return
  goal: maximize
parameters:
  alpha:
    values: [ 0.1, 0.4, 0.6, 0.7] # example alpha values
  learning_rate:
    values: [0.1, 0.3, 0.5]
  discount_factor:
    values: [0.9]
  exploration_rate:
    values: [1.0]
  exploration_decay_rate:
    values: [0.001]
  min_exploration_rate:
    values: [0.000001]

## sweep_random.yaml
#method: random
#metric:
#  name: average_return
#  goal: maximize
#parameters:
#  alpha:
#    distribution: uniform
#    min: 0.1
#    max: 0.99
#  learning_rate:
#    distribution: uniform
#    min: 0.0001
#    max: 0.1
#  discount_factor:
#    distribution: uniform
#    min: 0.5
#    max: 0.99
#  exploration_rate:
#    distribution: uniform
#    min: 0.1
#    max: 1.0
#  exploration_decay_rate:
#    distribution: uniform
#    min: 0.8
#    max: 0.998
#  min_exploration_rate:
#    distribution: uniform
#    min: 0.00000001
#    max: 0.00001

