# sweep.yaml
method: bayes
metric:
  name: average_return
  goal: maximize
parameters:
  alpha:
    values: [0.1, 0.3, 0.5, 0.7, 0.9] # example alpha values
  learning_rate:
    min: 0.01
    max: 0.1
  discount_factor:
    min: 0.8
    max: 0.99
  exploration_rate:
    min: 0.01
    max: 0.1
