# sweep.yaml
method: grid
metric:
  name: train/reward
  goal: maximize
parameters:
  alpha:
    values: [0.8, 0.9] # example alpha values
  learning_rate:
    values: [0.0001, 0.001]
  discount_factor:
    values: [0.9]
  exploration_rate:
    values: [1.0]
  exploration_decay_rate:
    values: [0.00001]
  min_exploration_rate:
    values: [0.000001]
  learning_rate_decay:
    values: [0.99995]
  min_learning_rate:
    values: [0.001]
  target_network_update_frequency:
    values: [20, 100]
  max_episodes:
    values: [4000, 6000]
  train_frequency:
    values: [50, 100, 200]

## sweep_random.yaml
#method: random
#metric:
#  name: average_return
#  goal: maximize
#parameters:
#  alpha:
#    distribution: uniform
#    min: 0.1
#    max: 0.99
#  learning_rate:
#    distribution: uniform
#    min: 0.0001
#    max: 0.1
#  discount_factor:
#    distribution: uniform
#    min: 0.5
#    max: 0.99
#  exploration_rate:
#    distribution: uniform
#    min: 0.1
#    max: 1.0
#  exploration_decay_rate:
#    distribution: uniform
#    min: 0.8
#    max: 0.998
#  min_exploration_rate:
#    distribution: uniform
#    min: 0.00000001
#    max: 0.00001

