# sweep.yaml
method: grid
metric:
  name: average_return
  goal: maximize
parameters:
  alpha:
    values: [ 0.01, 0.4, 0.7, 0.99] # example alpha values
  learning_rate:
    values: [0.001, 0.01]
  discount_factor:
    values: [0.99]
  exploration_rate:
    values: [0.01, 0.05]
