wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684363325.762294
    t:
      1:
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 24
      4: 3.8.5
      5: 0.15.2
      8:
      - 5
    framework: keras
